### ISSUE TITLE
Error installing from Docker

### ISSUE THREAD

**Issue by barreeeiroo** [valeriansaliou/vigil#25]
I have followed the README.me instructions:

> sudo docker pull valeriansaliou/vigil:v1.9.0

The path to config.cfg is valid, but this error comes when executing the run command:

> sudo docker run -p 8080:8080 -v /.../config.cfg -e RUST_BACKTRACE=1 valeriansaliou/vigil:v1.9.0
```
thread 'main' panicked at 'cannot find config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind
             at src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
   7: std::sync::once::Once::call_once::{{closure}}
   8: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:387
   9: <vigil::APP_CONF as core::ops::deref::Deref>::deref
  10: vigil::main
  11: std::rt::lang_start::{{closure}}
  12: main
  13: __libc_start_main
  14: _start
```

Any idea what can be wrong?

**Comment by valeriansaliou** [comment]
Hello! Can you try passing absolute paths?

Also, your command is incorrect, it should be formatted as such:

```
docker run -p 8080:8080 -v /path/to/your/vigil/config.cfg:/etc/vigil.cfg valeriansaliou/vigil:v1.9.0
```

Where the `/path/to/[..]` is the part you change. Keep the `/etc/vigil.cfg` part as-is.

**Comment by barreeeiroo** [comment]
@valeriansaliou Tested this now:

```
makeroidbuilder@makeroid-status ~> sudo docker run -p 8080:8080 -v /home/makeroidbuilder/config.cfg:/etc/config.cfg -e RUST_BACKTRACE=1 valeriansaliou/vigil:v1.9.0
thread 'main' panicked at 'cannot find config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:997:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:70
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   2: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:215
             at src/libstd/panicking.rs:478
   3: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   4: rust_begin_unwind
             at src/libstd/panicking.rs:312
   5: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   6: core::result::unwrap_failed
   7: std::sync::once::Once::call_once::{{closure}}
   8: std::sync::once::Once::call_inner
             at src/libstd/sync/once.rs:387
   9: <vigil::APP_CONF as core::ops::deref::Deref>::deref
  10: vigil::main
  11: std::rt::lang_start::{{closure}}
  12: main
  13: __libc_start_main
  14: _start
makeroidbuilder@makeroid-status ~> 
```

**Comment by valeriansaliou** [comment]
Check your Docker call, it's `/etc/vigil.cfg` not `/etc/config.cfg`; this path is local to the Docker image and should not be modified. It's mapped to `/home/makeroidbuilder/config.cfg` in your case.

**Comment by barreeeiroo** [comment]
Got it, thanks! :+1: 
It's now working, closing the issue
