### ISSUE TITLE
thread 'main' panicked at 'cannot find config file

### ISSUE THREAD

**Issue by LeviSnoot** [valeriansaliou/vigil#92]
Hi! I've been looking around at different status pages for my server, and Vigil seems like it's exactly what I'm looking for! Unfortunately I am stuck in the setup process. I've finished installing vigil-server via Cargo, and I've edited my $PATH to include `export PATH="${PATH}:~/.cargo/bin"`. When I run the `vigil` command it returns the following (including full backtrace since it may or may not be helpful):

```
thread 'main' panicked at 'cannot find config file: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/levi/.cargo/registry/src/github.com-1ecc6299db9ec823/vigil-server-1.21.2/src/config/reader.rs:22:53
stack backtrace:
   0:     0x557fe2d60183 - std::backtrace_rs::backtrace::libunwind::trace::h90af754674ffafa4
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x557fe2d60183 - std::backtrace_rs::backtrace::trace_unsynchronized::hd35318b4e6e81148
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557fe2d60183 - std::sys_common::backtrace::_print_fmt::h7571a6f5687a20d1
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x557fe2d60183 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he0119e0b769c2e9a
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x557fe2be817f - core::fmt::write::h2b69bbb8432077e1
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/fmt/mod.rs:1094:17
   5:     0x557fe2d5fad4 - std::io::Write::write_fmt::h46cf1a7fb24b0a65
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/io/mod.rs:1584:15
   6:     0x557fe2d5f655 - std::sys_common::backtrace::_print::h78ae9eccd44fa022
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x557fe2d5f655 - std::sys_common::backtrace::print::h09e94b2c5bb4dae0
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x557fe2d5f655 - std::panicking::default_hook::{{closure}}::hfc3b9f31beb26f15
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:208:50
   9:     0x557fe2d5ec1f - std::panicking::default_hook::h24b36b429c561a5b
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:225:9
  10:     0x557fe2d5ec1f - std::panicking::rust_panic_with_hook::hcd8fcee5516a9191
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:591:17
  11:     0x557fe2d78dd3 - std::panicking::begin_panic_handler::{{closure}}::h19af3da01a9817bd
  12:     0x557fe2d78d4c - std::sys_common::backtrace::__rust_end_short_backtrace::h0a6d1565730521c9
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x557fe2d78cfd - rust_begin_unwind
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/panicking.rs:493:5
  14:     0x557fe2b14380 - core::panicking::panic_fmt::h4cabb5e7744685f2
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/panicking.rs:92:14
  15:     0x557fe2b14a42 - core::result::unwrap_failed::ha412bb7b0e63ae4c
                               at /build/rust/src/rustc-1.53.0-src/library/core/src/result.rs:1355:5
  16:     0x557fe2e90305 - std::sync::once::Once::call_once::{{closure}}::h562ed193157340b5
  17:     0x557fe2b20b1d - std::sync::once::Once::call_inner::hf8c2fbdc6a679078
                               at /build/rust/src/rustc-1.53.0-src/library/std/src/sync/once.rs:418:21
  18:     0x557fe2e8fa49 - std::sync::once::Once::call_once::ha7e5d0b2b179f0c3
  19:     0x557fe2e85029 - vigil::main::h1614b92ea9614477
  20:     0x557fe2e62f11 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf23bd9d084628fcb
  21:     0x557fe2e84f25 - main
  22:     0x7f8ec4a3db25 - __libc_start_main
  23:     0x557fe2b2ea9e - _start
  24:                0x0 - <unknown>
```
Maybe I've missed something but I've been troubleshooting this since last night and I'm not sure where to find the solution. Any help is much appreciated!

**Comment by dd10-e** [comment]
Hey! You actually need to setup the `config.cfg` file in the folder where you running your command.

Look at : https://github.com/valeriansaliou/vigil/blob/master/config.cfg

**Comment by LeviSnoot** [comment]
> 
> 
> Hey! You actually need to setup the `config.cfg` file in the folder where you running your command.
> 
> Look at : https://github.com/valeriansaliou/vigil/blob/master/config.cfg

Ohh yeah that makes sense, thank you! I tried creating a blank config.cfg in /home/levi/vigil and when I ran the command I got a different output! Thanks for getting me on the right path so quickly!
